## Numpy basics in python

In [70]:
import numpy as np

### creating array from the list 

In [71]:
arr_1D = np.array([1,2,3,46,])
print("1D array:",arr_1D)

arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D array",arr_2D)

1D array: [ 1  2  3 46]
2D array [[1 2 3]
 [4 5 6]]


## creating array from the scratch

In [10]:
zeros = np.zeros((3,2))
print("zeroes array: \n",zeros)


ones=np.ones((4,7))
print("ones array: \n",ones)

fullArr = np.full((3,3),8)
print("fulll array: \n",fullArr)


ranArr = np.random.random((2,4))
print("random array: \n",ranArr)


sequenceArr = np.arange(0,20,2) # 20 is exclusive 

print(sequenceArr)

zeroes array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
ones array: 
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
fulll array: 
 [[8 8 8]
 [8 8 8]
 [8 8 8]]
random array: 
 [[0.37593585 0.42807115 0.52710147 0.21353557]
 [0.09776112 0.95053586 0.63342075 0.66080483]]
[ 0  2  4  6  8 10 12 14 16 18]


## vector and matrices and tensor 


In [15]:
vector = np.array([1,2,3])
print("vector: \n",vector)


matrix = np.array([[1,2,4],[5,9,8]])
print("matrix : \n",matrix)


tensor = np.array([
    [ 
    [1,2],[3,4]
    ],
    [
    [6,7],
    [8,9]
    ]
    ])
print("tensor: \n",tensor)

vector: 
 [1 2 3]
matrix : 
 [[1 2 4]
 [5 9 8]]
tensor: 
 [[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


## Array properties in numpy 

In [18]:
arr = np.array([[1,2,3],[4,5,0.6]])
print("shape:",arr.shape);
print("dimension:",arr.ndim);
print("size",arr.size);
print("data type",arr.dtype);

shape: (2, 3)
dimension: 2
size 6
data type float64


In [28]:
arr = np.arange(12); # last number is excluded in the array
print("original array:",arr)

reshapedArr = arr.reshape((3,4))
print("reshaped array :",reshapedArr)

flatneedArr = reshapedArr.flatten()
print("flattened array:",flatneedArr)

raveled = reshapedArr.ravel() # return view instead of copy
print("raveled array:",raveled)

transposedArr = reshapedArr.transpose();
print("transposed array:",transposedArr);



original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Operation in numpy

In [31]:
newArr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing:\n",newArr[1:7])
print("with steps:\n",newArr[2:8:2]);
print("negative indexing:\n",newArr[3:-3])

basic slicing:
 [2 3 4 5 6 7]
with steps:
 [3 5 7]
negative indexing:
 [4 5 6]


### Operation on 2-d arrays

In [35]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]] )
print("specific element:\n",arr_2d[0,2])
print("entire row:\n",arr_2d[1])
print("entire column:",arr_2d[:,1])

specific element:
 3
entire row:
 [4 5 6]
entire column: [2 5 8]


## sorting

In [36]:
unsortedArr= np.array([1,0,5,4,9,-1,0,18])
print("sorted array:",np.sort(unsortedArr))

sorted array: [-1  0  0  1  4  5  9 18]


### 2d array sorting in numpy 

In [40]:
arr_2d_unsorted = np.array([[1,2],[4,5],[6,7]]);
print("sorted 2d array by col:",np.sort(arr_2d_unsorted,axis=1))


sorted 2d array by col: [[1 2]
 [4 5]
 [6 7]]


In [42]:
# filter on the array 

filterArr = np.array([1,2,3,4,5,6,8,10,12]);
even_Number = filterArr[filterArr%2 ==0];
print(even_Number)

[ 2  4  6  8 10 12]


In [43]:
# filter with mask 

mask = filterArr > 6
print("numberes are greater then 6 :",filterArr[mask])

numberes are greater then 6 : [ 8 10 12]


### fancy indexing vs np.where()

In [45]:
fancy_idx = [0,3,6]
print("fancy indexes:",filterArr[fancy_idx])

where_result = np.where(filterArr > 10);
print("NP where:",filterArr[where_result])

fancy indexes: [1 4 8]
NP where: [12]


In [46]:
# condition array 
condition_arr = np.where(filterArr>5,"true","false")
print("conditional array:",condition_arr)

conditional array: ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


## Adding and removing data 

In [48]:
arr1 = np.array([1,2])
arr2 = np.array([4,5])

# concation of array 

combined = np.concat((arr1,arr2))
print("combined array:",combined)

combined array: [1 2 4 5]


### array compatibility

In [50]:
a=np.array([1,2,3]);
b=np.array([4,5,6,0]);
c=np.array([9,17,2]);

# in some case we have to check the shape of the array before combining them
print("compatibily shape:\n",a.shape == b.shape)

combined array:
 False


In [56]:
originalArr = np.array([[1,2],[4,5]]);
new_row = np.array([[2,1],[4,5]]);

## addding a new row in the array

arr_with_new_row = np.vstack((originalArr,new_row))
print("array with new row:\n",arr_with_new_row)

org_arr = np.array([[1],[3]])
new_col = np.array([[9],[0]]);
with_new_col=np.hstack((org_arr,new_col));
print("array with a new column:\n",with_new_col);


array with new row:
 [[1 2]
 [4 5]
 [2 1]
 [4 5]]
array with a new column:
 [[1 9]
 [3 0]]


In [60]:
# deletion in array 

new_arr = np.array([1,2,3,4,6]);
print("new array:\n",new_arr);
deleted_arr=np.delete(new_arr,0)
print("deleted array:\n",deleted_arr)

new array:
 [1 2 3 4 6]
deleted array:
 [2 3 4 6]


## Advance operation with business example 

### data structure : [restaurant_id,2021,2022,2023,2024,2025 ]

- sales_data = np.array([
    [1,25000,26000,27000,28000,29000], #company1
    [2,35000,36000,37000,38000,39000], #company2
     [3,45000,46000,47000,48000,49000],#company3
     [4,55000,56000,57000,58000,59000] #company4

])

In [69]:
import matplotlib.pyplot as mat

sales_2d_arr = np.array([
    [1,25000,26000,27000,28000,29000], 
    [2,35000,36000,37000,38000,39000], 
    [3,45000,46000,47000,48000,49000],
    [4,55000,56000,57000,58000,59000]
])

print("zomato sales analysis")

print("sales data shape",sales_2d_arr.shape)

print("sales array data:\n",sales_2d_arr)

print("sales  array output with new slicing\n",sales_2d_arr[0 :3])
print("sales  array output with specific slicing:\n",sales_2d_arr[:,:])

## total sales per year 
print("total sales per year:\n", )

zomato sales analysis
sales data shape (4, 6)
sales array data:
 [[    1 25000 26000 27000 28000 29000]
 [    2 35000 36000 37000 38000 39000]
 [    3 45000 46000 47000 48000 49000]
 [    4 55000 56000 57000 58000 59000]]
sales  array output:
 [[    1 25000 26000 27000 28000 29000]
 [    2 35000 36000 37000 38000 39000]
 [    3 45000 46000 47000 48000 49000]]
sales  array output with specific slicing:
 [[    1 25000 26000 27000 28000 29000]
 [    2 35000 36000 37000 38000 39000]
 [    3 45000 46000 47000 48000 49000]
 [    4 55000 56000 57000 58000 59000]]
