In [2]:
import numpy as np # importing the numpy library 

## Basic of array Creation 

In [3]:
# 1D arrays 


arr = np.array([1,2,3,4,4]) # array creation 

print("1 D array")
print(arr)

print(type(arr))


# 2 D arrays creation 

arr2 = np.array([
    [1,2,3], #first row
    [4,5,6], #second row
    [7,8,9]  #third row
    ])
print("2D array")
print(arr2)


# 3 D array 

arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
    [7,8,9],
    [10,11,12]
    ]
    ])
print("3 D array")
print(arr3)


# to check the dimension of the array 
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1 D array
[1 2 3 4 4]
<class 'numpy.ndarray'>
2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3


## Shape  in the numpy array 

In [ ]:

#Shape of the array specify the number  row and column in array

print(arr.shape)
print(arr2.shape)
print(arr3.shape)

## Arrray generation function 

In [41]:
# array generation functions 

arr = np.arange(0,10) # it will generate array from 0 to 9
print("array using arange function : \n", arr)


arr = np.zeros((4,4)) # it will generate 3x4 array with all values as zero
print("array using zeros function : \n", arr)

arr = np.ones((5,5))
print("array using ones function : \n", arr)


arr = np.linspace(0,100, num=5) # it will generate 5 values between 0 to 100
print("array using linspace function : \n", arr)

array using arange function : 
 [0 1 2 3 4 5 6 7 8 9]
array using zeros function : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array using ones function : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array using linspace function : 
 [  0.  25.  50.  75. 100.]


# Indexing in array

In [21]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])


print(array[3])

# 2 d array access 

arrr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arrr2[-3,-3])  # accessing element at 2nd row and 3rd column

4
1


# Slicing in the array 

In [22]:
print(array[0:5:2])

# negative slicing 

print(array[-2:-1])


print(array.dtype) # to check the datatype of the array elements

# creating array with specific data type
arr_float = np.array([1,2,3,4,5], dtype='float64')

print(arr_float.dtype)





[1 3 5]
[4]
int64
float64


In [23]:
# converting the  data type of existing array 

arr = np.array([1.1,2.2,3.6,4.7,5.9])

new_arr = arr.astype('int32')
print(arr)
print(new_arr)
print(new_arr.dtype)

[1.1 2.2 3.6 4.7 5.9]
[1 2 3 4 5]
int32


## Deep copy vs shallow copy

In [ ]:
# copy vs view in the array 

arr = np.array([1,2,3,4,5])
arr_copy = arr.copy() # shallow copy
arr[0]=11

print(arr)
print(arr_copy)

# view example
arr = np.array([1,2,3,4,5])
arr_view = arr.view() # deep copy
arr[0]=11
print(arr)
print(arr_view)

[11  2  3  4  5]
[1 2 3 4 5]
[11  2  3  4  5]
[11  2  3  4  5]


# Reshaping in the array 

In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print("original array")
print(arr)

print("reshaped array 2d array")
print(arr.reshape(3,5))  # 3 rows and 5 columns



print("reshaped array 3d array")
print(arr.reshape(3,1,5))  # 3 layers , 1 row and 5 columns

# any changes made in reshaped array will affect original array

original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped array 2d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
reshaped array 3d array
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [26]:
# falattening the array

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


##  Iteration in the numpy array 

In [27]:
arr = np.array([1,2,3,4,5])

for i in arr:
    print(i,end=',')

1,2,3,4,5,

In [28]:
# iterating 2 d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


for i in arr:
    for j in i:
        print(j,end=',')

    print()    

1,2,3,
4,5,6,
7,8,9,


In [29]:
# iteration using nditer()
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in np.nditer(arr):
    print(x,end=",")


print('\n')

# iteration with different data types

for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x,end=",")  



print('\n')

# iteration with different step size

for x in np.nditer(arr[:,::2]):
    print(x,end=",")


1,2,3,4,5,6,7,8,9,

np.bytes_(b'1'),np.bytes_(b'2'),np.bytes_(b'3'),np.bytes_(b'4'),np.bytes_(b'5'),np.bytes_(b'6'),np.bytes_(b'7'),np.bytes_(b'8'),np.bytes_(b'9'),

1,3,4,6,7,9,

## join in numpy

In [30]:
# join in numpy 

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2),axis=0)

print(arr3)


new_arr1 = np.array([
    [1,2,3],
    [4,5,6]
    ])
new_arr2 = np.array([
    [7,8,9],
    [10,11,12]
    ])

new_arr3 = np.concatenate((new_arr1,new_arr2),axis=1)

print(new_arr3)

[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Advance array manipulation

In [62]:
# Stacking in the array 

a = np.array([1,2,3])
b =  np.array([4,5,6])

stacked_arr = np.stack((a,b),axis=0) # stacking along the column
print(stacked_arr)
np.vstack((a,b)) # stacking along the row
np.hstack((a,b)) # stacking along the row
np.column_stack((a,b)) # stacking along the column

# splitting of the array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = np.array_split(arr,3) #  return a list contain 3 array 
print(new_arr)

print(new_arr[0]) # accessing the first array 


# if the array doesnt  have the required number of elements then it will adjust acccordingly

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11])
new_arr2 = np.array_split(arr2,3)
print(new_arr2)



# split the 2d array

arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr3 = np.array_split(arr3, 3)

print(newarr3)

newarr4 = np.array_split(arr3, 3, axis=1) # spliting along the column
print(newarr4)

[[1 2 3]
 [4 5 6]]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[1 2 3 4]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


## Searching in the array 

In [32]:
# searching in  numpy array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

x = np.where(arr==9) # return the index of the matched element

y = np.where(arr%2==1) # return the index of all even elements

print(x)
print(y)

(array([8]),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14]),)


In [33]:
# sorting the numpy array 

arr = np.array([3,6,1,8,4,5,9,2,7])

print("original array")
print(arr)

print("sorted array")
print(np.sort(arr)) # return a sorted array without changing the original array 


# sorting on a 2 d array 

arr2 = np.array([[3,6,1],[8,4,5],[9,2,7]])
print(np.sort(arr2)) 

original array
[3 6 1 8 4 5 9 2 7]
sorted array
[1 2 3 4 5 6 7 8 9]
[[1 3 6]
 [4 5 8]
 [2 7 9]]


## random module in numpy

In [ ]:
# Numpy random modules 

from numpy import random

x = random.randint(100) # random integer between 0 to 100
print(x)

y = random.randn() # random float between 0 to 1
print(y)

# we can create the array of random  numbers 

z = random.randint(100,size=(5)) # 1 d array of size 5
print(z)

k = random.rand(5)
print(k)

66
0.4955185424499394
[10 66 45 11 70]
[0.81448686 0.36319094 0.04733753 0.31465027 0.26067542]


## Matrix Operation in array 

In [58]:
#Operation in the numpy array

arr = np.array([1,2,3,4,5])

print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.sum(axis=0)) # use in case of the 2d array 

arr1 = np.array([[1,2],[4,5]])


arr2 = np.array([[10,11],[13,14]])

np.dot(arr1,arr2) # dot product of two arrays

np.transpose(arr1) # transpose of the array


15
3.0
1.4142135623730951
15


array([[1, 4],
       [2, 5]])