In [2]:
import numpy as np 

In [3]:
# 1D arrays 


arr = np.array([1,2,3,4,4])

print("1 D array")
print(arr)

print(type(arr))


# 2 D arrays 

arr2 = np.array([
    [1,2,3], #first row
    [4,5,6], #second row
    [7,8,9]  #third row
    ])
print("2D array")
print(arr2)


# 3 D array 

arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
    [7,8,9],
    [10,11,12]
    ]
    ])
print("3 D array")
print(arr3)


# to check the dimension of the array 
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1 D array
[1 2 3 4 4]
<class 'numpy.ndarray'>
2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3


In [ ]:

#Shape of the array specify the number  row and column in array

print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(3, 3)
(2, 2, 3)


# Indexing

In [31]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])


print(array[3])

# 2 d array access 

arrr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arrr2[-3,-3])  # accessing element at 2nd row and 3rd column

4
1


# Slicing in the array 

In [46]:
print(array[0:5:2])

# negative slicing 

print(array[-2:-1])


print(array.dtype) # to check the datatype of the array elements

# creating array with specific data type
arr_float = np.array([1,2,3,4,5], dtype='float64')

print(arr_float.dtype)





[1 3 5]
[4]
int64
float64


In [48]:
# converting the  data type of existing array 

arr = np.array([1.1,2.2,3.6,4.7,5.9])

new_arr = arr.astype('int32')
print(arr)
print(new_arr)
print(new_arr.dtype)

[1.1 2.2 3.6 4.7 5.9]
[1 2 3 4 5]
int32


In [51]:
# copy vs view in the array 

arr = np.array([1,2,3,4,5])
arr_copy = arr.copy()
arr[0]=11

print(arr)
print(arr_copy)

# view example
arr = np.array([1,2,3,4,5])
arr_view = arr.view()
arr[0]=11
print(arr)
print(arr_view)

[11  2  3  4  5]
[1 2 3 4 5]
[11  2  3  4  5]
[11  2  3  4  5]


# Reshaping in the array 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print("original array")
print(arr)

print("reshaped array 2d array")
print(arr.reshape(3,5))  # 3 rows and 5 columns



print("reshaped array 3d array")
print(arr.reshape(3,1,5))  # 3 layers , 1 row and 5 columns

# any changes made in reshaped array will affect original array

original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped array 2d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
reshaped array 3d array
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [61]:
# falattening the array

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


##  Iteration in the numpy array 

In [65]:
arr = np.array([1,2,3,4,5])

for i in arr:
    print(i,end=',')

1,2,3,4,5,

In [4]:
# iterating 2 d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


for i in arr:
    for j in i:
        print(j,end=',')

    print()    

1,2,3,
4,5,6,
7,8,9,


In [15]:
# iteration using nditer()
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in np.nditer(arr):
    print(x,end=",")


print('\n')

# iteration with different data types

for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x,end=",")  



print('\n')

# iteration with different step size

for x in np.nditer(arr[:,::2]):
    print(x,end=",")


1,2,3,4,5,6,7,8,9,

np.bytes_(b'1'),np.bytes_(b'2'),np.bytes_(b'3'),np.bytes_(b'4'),np.bytes_(b'5'),np.bytes_(b'6'),np.bytes_(b'7'),np.bytes_(b'8'),np.bytes_(b'9'),

1,3,4,6,7,9,

In [ ]:
# join in numpy 

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1,arr2),axis=0)

print(arr3)


new_arr1 = np.array([
    [1,2,3],
    [4,5,6]
    ])
new_arr2 = np.array([
    [7,8,9],
    [10,11,12]
    ])

new_arr3 = np.concatenate((new_arr1,new_arr2),axis=1)

print(new_arr3)

[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# splitting of the array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = np.array_split(arr,3) #  return a list contain 3 array 
print(new_arr)

print(new_arr[0]) # accessing the first array 


# if the array doesnt  have the required number of elements then it will adjust acccordingly

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11])
new_arr2 = np.array_split(arr2,3)
print(new_arr2)



# split the 2d array

arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr3 = np.array_split(arr3, 3)

print(newarr3)

newarr4 = np.array_split(arr3, 3, axis=1) # spliting along the column
print(newarr4)

In [27]:
# searching in  numpy array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

x = np.where(arr==9) # return the index of the matched element

y = np.where(arr%2==1) # return the index of all even elements

print(x)
print(y)

(array([8]),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14]),)


In [ ]:
# sorting the numpy array 

arr = np.array([3,6,1,8,4,5,9,2,7])

print("original array")
print(arr)

print("sorted array")
print(np.sort(arr)) # return a sorted array without changing the original array 


# sorting on a 2 d array 

arr2 = np.array([[3,6,1],[8,4,5],[9,2,7]])
print(np.sort(arr2)) 

original array
[3 6 1 8 4 5 9 2 7]
sorted array
[1 2 3 4 5 6 7 8 9]
[[3 2 1]
 [8 4 5]
 [9 6 7]]


In [46]:
# Numpy random modules 

from numpy import random

x = random.randint(100) # random integer between 0 to 100
print(x)

y = random.rand() # random float between 0 to 1
print(y)

# we can create the array of random  numbers 

z = random.randint(100,size=(5)) # 1 d array of size 5
print(z)

k = random.rand(5)
print(k)

48
0.9861383976513524
[20 32 84 71 30]
[0.22553603 0.56960815 0.11243604 0.03729327 0.09897188]
