In [2]:
import pandas as pd
import numpy as np

In [3]:
# create a sample DataFrame

df = pd.DataFrame(np.arange(1,26).reshape(5,5),index=['A','B','C','D','E'],columns=['W','X','Y','Z','Q']
                  )

In [ ]:
# printing the created DataFrame
df

W   X   Y   Z   Q
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [ ]:
# acessing the element in the data frame 
# 1. loc method 2. iloc method

print(df.loc['A'])

print(type(df.loc['A'])) # series

print(df.iloc[0:3,0:2])

print(type(df.iloc[0:3,0:2])) # data frame

W    1
X    2
Y    3
Z    4
Q    5
Name: A, dtype: int64
<class 'pandas.core.series.Series'>
    W   X
A   1   2
B   6   7
C  11  12
<class 'pandas.core.frame.DataFrame'>


In [15]:
# convert the data frame  into array 

array_data = df.values

print(array_data)
print(type(array_data)) # numpy array
print(array_data.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
<class 'numpy.ndarray'>
(5, 5)


In [ ]:
# splitting of the array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = np.array_split(arr,3) #  return a list contain 3 array 
print(new_arr)

print(new_arr[0]) # accessing the first array 


# if the array doesnt  have the required number of elements then it will adjust acccordingly

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11])
new_arr2 = np.array_split(arr2,3)
print(new_arr2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[1 2 3 4]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]
